# Github action to build sphinx site and commit to gh-pages branch
#
#  Built site is pushed to 'gh-pages' branch
#

name: Sphinx Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        
    - name: Checkout page source
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4

    - name: Install sphinx
      run: pip3 install --user -r requirements.txt
      
    - name: adapt the sphinx site to jekyll sitemap
      run: python jekyll_sitemap.py
      
    - name: delete _data folder
      run: rm -Rf _data
      
    - name: download _data
      run: mkdir _data && cd _data && gh run download -n _data
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build page
      run: make dirhtml
      
    - run: touch build/html/.nojekyll

    - name: Deploy documentation sphinx
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build/html
        clean: false
