# Github action to build sphinx site and commit to gh-pages branch
#
#  Built site is pushed to 'gh-pages' branch
#

name: Sphinx Build

on:
  push:
    branches: [ master ]

env:
  SRC_DIR: src
  PUBLISH_DIR: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        
    - name: Checkout page source
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install sphinx
      run: pip3 install --user -r requirements.txt
      
    - name: Build page
      run: make html
      
    - run: touch build/html/.nojekyll

    - name: Deploy documentation sphinx
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build/html
        clean: false
